// GENERATED by @edgedb/generate v0.1.1
// Run 'npx @edgedb/generate edgeql-js' to re-generate

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
export type $CreatedAtλShape = $.typeutil.flatten<_std.$Object_ff41cb16eb7a11ed88b3abb440daad75λShape & {
  "created_at": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, true, true>;
}>;
type $CreatedAt = $.ObjectType<"has::CreatedAt", $CreatedAtλShape, null, [
  ..._std.$Object_ff41cb16eb7a11ed88b3abb440daad75['__exclusives__'],
]>;
const $CreatedAt = $.makeType<$CreatedAt>(_.spec, "08549b10-f55e-11ed-ae1b-ab0c454e4b79", _.syntax.literal);

const CreatedAt: $.$expr_PathNode<$.TypeSet<$CreatedAt, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($CreatedAt, $.Cardinality.Many), null);



export { $CreatedAt, CreatedAt };

type __defaultExports = {
  "CreatedAt": typeof CreatedAt
};
const __defaultExports: __defaultExports = {
  "CreatedAt": CreatedAt
};
export default __defaultExports;
