// GENERATED by @edgedb/generate v0.1.0
// Run 'npx @edgedb/generate edgeql-js' to re-generate

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
export type $CreatedAtλShape = $.typeutil.flatten<_std.$Object_6957daacebaf11ed9a17df80308ab3e6λShape & {
  "created_at": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, true, true>;
}>;
type $CreatedAt = $.ObjectType<"has::CreatedAt", $CreatedAtλShape, null, [
  ..._std.$Object_6957daacebaf11ed9a17df80308ab3e6['__exclusives__'],
]>;
const $CreatedAt = $.makeType<$CreatedAt>(_.spec, "c444db6c-ebf6-11ed-99de-1f8025f12019", _.syntax.literal);

const CreatedAt: $.$expr_PathNode<$.TypeSet<$CreatedAt, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($CreatedAt, $.Cardinality.Many), null);



export { $CreatedAt, CreatedAt };

type __defaultExports = {
  "CreatedAt": typeof CreatedAt
};
const __defaultExports: __defaultExports = {
  "CreatedAt": CreatedAt
};
export default __defaultExports;
